services:
  - type: web
    name: ai-interview-system
    env: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-interview-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false

databases:
  - name: ai-interview-db
    plan: free
